language: node_js
node_js:
  - 10.13
  - 12.13

addons:
  sonarcloud:
    organization: "sogame-github"

install:
  - npm ci --quiet
  - npm install -g danger-plugin-toolbox@1.18.0
  - npm link danger-plugin-toolbox # Link the global version of "danger-plugin-toolbox" into the local "node_modules/"

script:
  - (set -o pipefail; npm run lint |& tee lint.log);
  - (set -o pipefail; npm run test:coverage |& tee test.log);
  - npm run danger
  - npm run spellcheck:ci
  - sonar-scanner # SonarCloud
